name: Android Build (Debug + Release + Tests)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Instalar Android SDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
          unzip -q sdk.zip -d $ANDROID_HOME/cmdline-tools
          
          # Renomeia para o caminho esperado 'latest'
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Adiciona as ferramentas do SDK ao PATH do sistema
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          # Aceita as licenças e instala os pacotes necessários
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" > /dev/null

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew

      - name: Restaurar Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/release-key.jks

      - name: Rodar testes
        run: |
          unset ANDROID_SDK_ROOT
          ./gradlew test --stacktrace

      - name: Upload Relatórios de Teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-de-teste
          path: app/build/reports/tests/testDebugUnitTest/
          if-no-files-found: warn

      - name: Build Debug
        run: |
          unset ANDROID_SDK_ROOT
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Build Release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }} # Adicione esta variável se a senha da chave for diferente da senha do keystore
        run: |
          unset ANDROID_SDK_ROOT
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
