name: Android Build (Debug + Release + Tests)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Instalar Android SDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip

          mkdir -p $ANDROID_HOME/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
          unzip sdk.zip -d $ANDROID_HOME/cmdline-tools

          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"

          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

          yes | $SDKMANAGER --licenses
          $SDKMANAGER "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew

      - name: Restaurar Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > release-key.jks

      - name: Rodar testes
        run: ./gradlew test --stacktrace --info

      - name: Upload Relatórios de Teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-de-teste
          path: app/build/test-results/test

      - name: Build Debug
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Build Release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: ./gradlew assembleRelease --stacktrace --info

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
          
